/*
 * Copyright (C) 2023 Amazon.com, Inc. or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * CDK Nag for Opensearch Domain
 *
 * @group nag/opensearch-domain
 */

import { App, Stack } from 'aws-cdk-lib';
import { SubnetType, Vpc } from "aws-cdk-lib/aws-ec2";

import { OpenSearchDomain } from '../../src'
import {
  acknowledge,
  acknowledgeByPath,
  getNagErrors
} from './acknowledge';

const mockApp = new App();
const mockStack = new Stack(mockApp, 'NagStack');

// Instantiate Construct
new OpenSearchDomain(mockStack, 'opensearch', {
  vpc: new Vpc(mockStack, 'vpc', {subnetConfiguration: [{
      cidrMask: 24,
      name: 'ingress',
      subnetType: SubnetType.PUBLIC,
    },
    {
      cidrMask: 24,
      name: 'application',
      subnetType: SubnetType.PRIVATE_WITH_EGRESS,
    },
    {
      cidrMask: 28,
      name: 'rds',
      subnetType: SubnetType.PRIVATE_ISOLATED,
    }]})
})


acknowledgeByPath(
    mockStack,
    '/NagStack/vpc/Resource',
    [{ id: 'AwsSolutions-VPC7', reason: 'VPC is provided by the customer, not part of the construct' }],
);

acknowledgeByPath(
    mockStack,
    '/NagStack/opensearch/Userpool/Resource',
    [
      { id: 'AwsSolutions-COG3', reason: 'AdvancedSecurityMode incurs additional costs to the user. They can provide their own user pool if they want to enable it.' },
      { id: 'AwsSolutions-COG8', reason: 'The Plus tier incurs additional costs. Customers can provide their own user pool if required.' },
    ],
);

acknowledgeByPath(
  mockStack,
  '/NagStack/opensearch/SecurityGroup/Resource',
  [{
    id: 'AwsSolutions-EC23',
    reason: 'The VPC CIDR is unresolved until CloudFormation deployment.'
  }]
);

acknowledge(mockStack, [
  { id: 'AwsSolutions-IAM4', reason: 'Using standard managed policies' }
]);


acknowledgeByPath(
    mockStack,
    '/NagStack/opensearch/Domain/Resource',
    [
        { id: 'AwsSolutions-OS3', reason: 'Customer can enable this with construct parameters, not by default' },
        { id: 'AwsSolutions-OS4', reason: 'Customer can enable this with construct parameters, not by default (additional costs)' },
        { id: 'AwsSolutions-OS7', reason: 'Customer can enable this with construct parameters, not by default (additional costs)' },
        { id: 'AwsSolutions-OS9', reason: 'Customer can enable this with construct parameters, not by default' }
    ],
);

acknowledgeByPath(
    mockStack,
    '/NagStack/AWS679f53fac002430cb0da5b7982bd2287/Resource',
    [
      { id: 'AwsSolutions-L1', reason: 'Function generated by a CDK construct' },
    ],
);

acknowledge(mockStack, [
  { id: 'AwsSolutions-IAM4', reason: 'Using standard managed policies' }
]);

describe('CDK Nag', () => {

  test('No unsuppressed Errors', () => {
    expect(getNagErrors(mockStack)).toHaveLength(0);
  });

});
