/**
 * The Pandoc output types supported by the
 * `PandocTextConverter` middleware.
 */
export type PandocOutput = 'asciidoc'
  | 'bibtex'
  | 'commonmark'
  | 'context'
  | 'csljson'
  | 'docbook'
  | 'docbook4'
  | 'docbook5'
  | 'docx'
  | 'dokuwiki'
  | 'epub'
  | 'epub2'
  | 'epub3'
  | 'fb2'
  | 'gfm'
  | 'haddock'
  | 'html'
  | 'html4'
  | 'html5'
  | 'icml'
  | 'ipynb'
  | 'jats'
  | 'jira'
  | 'json'
  | 'latex'
  | 'man'
  | 'markdown'
  | 'markdown_github'
  | 'markdown_mmd'
  | 'markdown_phpextra'
  | 'markdown_strict'
  | 'markua'
  | 'mediawiki'
  | 'muse'
  | 'odt'
  | 'opml'
  | 'pdf'
  | 'plain'
  | 'pptx'
  | 'rst'
  | 'rtf'
  | 'texinfo'
  | 'textile'
  | 'xwiki'
  | 'zimwiki';