name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
  pull_request:
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # Lint the code and check for spelling errors.
  lint:
    uses: ./.github/workflows/run-lint.yml

  # Build the documentation.
  build:
    needs: lint
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Install, build, and upload documentation
        uses: withastro/action@44706356b4eb735f8b9035699eb4796241a040c4
        with:
          path: ./docs
          node-version: 24
          package-manager: npm@11.12.0

  # Deploy the documentation to GitHub Pages.
  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@854d7aa1b99e4509c4d1b53d69b7ba4eaf39215a
