name: Release Packages

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          fetch-depth: 0
      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install jq
      - name: Install dependencies
        run: npm install
      - name: Build all packages
        run: npm run build
      - name: Setup auth tokens
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GH_PUBLISH_TOKEN }}@github.com/$GITHUB_REPOSITORY
          npm set "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}"
      - name: Version
        run: |
          npx lerna version minor --no-changelog --no-commit-hooks --no-private --yes
      - name: Release packages
        run: |
          npx lerna publish from-git --no-private --no-changelog --yes --throttle --throttle-size 1 --throttle-delay 2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Set release version
        id: set-release-version
        run: |
          VERSION=$(cat lerna.json | jq .version -r)
          echo RELEASE_VERSION="$VERSION" >> "$GITHUB_OUTPUT"
