name: Run lint checks on the project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      # Checkout and setup.
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      # Set node version.
      - name: Set node version
        uses: actions/setup-node@802632921f8532d2409ae6eac3313b6f81f11122
        with:
          node-version: 20

      # Link Checker.
      - name: Link Checker
        uses: lycheeverse/lychee-action@c053181aa0c3d17606addfe97a9075a32723548a
        with:
          fail: true
          args: --scheme=https . --exclude-all-private --exclude npmjs.com

      # Install dependencies.
      - name: Install dependencies
        run: npm install

      # Run linting.
      - name: Run linting
        run: npm run lint

      # Spell check.
      - name: Spell check
        uses: streetsidesoftware/cspell-action@4dc9d4bdf3974ed26d6f2e973c1e168edff47d80
        with:
          files: '**/*.{md,ts}'
          strict: true
          check_dot_files: true
          incremental_files_only: false
          config: 'cspell.config.yml'

      # ShellCheck.
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@cd81f4475ab741e097ec0fe73b692f3e49d66b8c
        with:
          scandir: '.'
          ignore_paths: >-
            node_modules
            .husky
