name: Run security checks on the project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      # Checkout and setup.
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      # Set node version.
      - name: Set node version
        uses: actions/setup-node@802632921f8532d2409ae6eac3313b6f81f11122
        with:
          node-version: 20
      
      # Install dependencies.
      - name: Install dependencies
        run: npm install
      
      # NPM audit.
      - name: Run audit
        run: npm audit

      # GitLeaks.
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@4df650038e2eb9f7329218df929c2780866e61a3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

      # Checkov.
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@d403349a9193cf87f58f18a0f09aab1e9e058bde
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          skip_check: CKV_DOCKER_2,CKV_DOCKER_3

      # Bandit.
      - name: Run Bandit
        uses: tj-actions/bandit@d7f9d3e6020f1b252bc82edd32757ba5bf115f16
        with:
          targets: './packages'
          options: '-r -c bandit.yml'
