name: Run unit tests and builds the project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [20, 22]
    steps:
      # Checkout and setup.
      - name: Checkout repository
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2

      # Set node version.
      - name: Set node version
        uses: actions/setup-node@802632921f8532d2409ae6eac3313b6f81f11122
        with:
          node-version: ${{ matrix.version }}

      # Install dependencies.
      - name: Install dependencies
        run: npm install

      # Build all packages.
      - name: Build all packages
        run: npm run build

      # Run linting.
      - name: Run linting
        run: npm run lint

      # Run unit tests.
      - name: Run unit tests
        run: npm test
