name: Run lint checks on the project

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

      # Checkout and setup.
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      # Set node version.
      - name: Set node version
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: 24

      # Install dependencies.
      - name: Install dependencies
        run: npm install

      # Spell check.
      - name: Spell check
        uses: streetsidesoftware/cspell-action@6f3c77c1406bc930f944ba97e9801a22e42caf58
        with:
          files: '**/*.{md,ts}'
          strict: true
          check_dot_files: true
          incremental_files_only: false
          config: 'cspell.config.yml'

      # ShellCheck.
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@cd81f4475ab741e097ec0fe73b692f3e49d66b8c
        with:
          scandir: '.'
          ignore_paths: >-
            node_modules
            .husky
